### ISSUE TITLE
Error: Cannot find module '@ethersproject/address'

### ISSUE THREAD

**Issue by chaitanya5** [Uniswap/uniswap-sdk#44]
Steps to reproduce

`npm i @uniswap/sdk`

In my Index.js file

`const UNISWAP = require('@uniswap/sdk')
console.log(`The chainId of mainnet is ${UNISWAP.ChainId.MAINNET}.`)`

Error: 
`$ node index.js 
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module '@ethersproject/address'
Require stack:
- C:\Users\ROUT SAINGYUKTA\Documents\Uniswap\node_modules\@uniswap\sdk\dist\sdk.cjs.development.js
- C:\Users\ROUT SAINGYUKTA\Documents\Uniswap\node_modules\@uniswap\sdk\dist\index.js
- C:\Users\ROUT SAINGYUKTA\Documents\Uniswap\index.js
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:841:27)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:1025:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:72:18)←[39m
    at Object.<anonymous> (C:\Users\ROUT SAINGYUKTA\Documents\Uniswap\node_modules\←[4m@uniswap←[24m\sdk\dist\sdk.cjs.development.js:10:15)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1137:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:985:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:878:14)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:1025:19)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [
    ←[32m'C:\\Users\\ROUT SAINGYUKTA\\Documents\\Uniswap\\node_modules\\@uniswap\\sdk\\dist\\sdk.cjs.development.js'←[39m,
    ←[32m'C:\\Users\\ROUT SAINGYUKTA\\Documents\\Uniswap\\node_modules\\@uniswap\\sdk\\dist\\index.js'←[39m,
    ←[32m'C:\\Users\\ROUT SAINGYUKTA\\Documents\\Uniswap\\index.js'←[39m
  ]
}`

**Comment by chaitanya5** [comment]
I found the work around, npm i @uniswap/sdk installs 3.0.3 version which caused the error.
Downgrading to npm in @uniswap/sdk@3.0.2 fixed it.
